### ISSUE TITLE
Script is looking for wrong snapshot names and fails when child and parent are diffrent

### ISSUE THREAD

**Issue by Pitastic** [dapuru/zfsbackup#10]
I create snapshots with periodic tasks and use this script which creates also snapshots. The result for one of my dataset is this list of snapshots for example:

```
# Storage			# Backup
Dokumente@20220101-1200		Dokumente@20220101-1200
Dokumente@20220202-1300		Dokumente@20220202-1300
- None -			Dokumente@20220202-1330
Dokumente/Child@20220101-1200	Dokumente/Child@20220101-1200
Dokumente/Child@20220101-1300	Dokumente/Child@20220101-1300
Dokumente/Child@20220203-1330	Dokumente/Child@20220203-1330
```

As you can see, parent and child snapshotlist is not equal on storage and one even not equal to backup.

The following line of the script is looking for the most recent snapshot (to use this value in `zfs send`) :

https://github.com/dapuru/zfsbackup/blob/3a81bc4a29f2d3ffcff8d8033ec4875268774c65/truenas-poolbackup.sh#L224

This is unfortunately not accurate as it would find the snapshotname `Dokumente/Child@20220203-1330` in my example which causes the script to fail as there is no corresponding `Dokumente@20220203-1330` snapshot.

Maybe every datasets snapshot (child or parent) have to be looked up on its own?

**Comment by Pitastic** [comment]
Also it would be generelly good to check this before hand for all datasets and take snapshot from all datasets **before** starting the heavy stuff.

**Comment by Pitastic** [comment]
Clarifying:

The condition in the next line `if [ "$recentBSnap" != "$origBSnap" ]` should handle exactly this situation (compare snapshots in backup and storage). It just fails because a snapshot name exists for a childdataset.

~~The value of `$origBSnap` should get retrieved in the way like `$recentBSnap` not with a `grep` to prevent these situations.~~

**Comment by dapuru** [comment]
Will look into this later.. may take some time

**Comment by Pitastic** [comment]
I may overcomplicated this thing. The main issue was that `grep` just looks for the snapshotname anywhere in the list (not taking the exact dataset name into account). 

I fixed it in the PR whit sth. like `... | grep "${DATASET}@${PREFIX}-" ...` instead of `... | grep "@${PREFIX}-" ...`
