### ISSUE TITLE
backup stops when started by devd - completes when started in screen session 

### ISSUE THREAD

**Issue by storchi** [dapuru/zfsbackup#16]
hi, me again.
when started with devd the script stops reproducibly at this point:

> cat 2024-02-22_07-55-07-backup.log
> Running on freebsd
> ########## Backup of pools on NAS-YVP ##########
> Started Backup-job: 2024-02-22_07-55-07
> 
> +--------------+--------+------------+--------+
> |Dataset       |Size    |Snapcount   |SnapSize |
> +--------------+--------+------------+--------+
> | Dataset | 3.17T | none | 0B |
> +--------------+--------+------------+--------+
> | Dataset/Austausch | 328G | none | 2.61M |
> +--------------+--------+------------+--------+
> | Dataset/Org | 496G | none | 30.1M |
> +--------------+--------+------------+--------+
> | Dataset/Projekte | 2.33T | none | 1.08G |
> +--------------+--------+------------+--------+
> | Dataset/ProjekteIntern | 32.2G | none | 37.4M |
> +--------------+--------+------------+--------+
> | Dataset/ScanOrdner | 773M | none | 1.17M |
> +--------------+--------+------------+--------+
>   pool: pool-backup2
>  state: ONLINE
>   scan: scrub repaired 0B in 1 days 00:06:26 with 0 errors on Thu Jan 25 10:16:29 2024
> config:
> 
> 	NAME                                          STATE     READ WRITE CKSUM
> 	pool-backup2                                  ONLINE       0     0     0
> 	  gptid/bd972045-b0af-11ee-810a-ece7a7077b48  ONLINE       0     0     0
> 
> errors: No known data errors
> 
> ****************** data / Dataset ******************
> most current snapshot in Backup: pool-backup2/Dataset@back-script-20240214-091013
> new snapshot created: data/Dataset@back-script-20240222-075532
> Send: data/Dataset@back-script-20240222-075532 to pool-backup2/Dataset
> Destroying Snapshots for Dataset:
> pool-backup2/Dataset@back-script-20240214-084453
> data/Dataset@back-script-20240214-084453
> 
> ****************** data / Dataset/Austausch ******************
> most current snapshot in Backup: pool-backup2/Dataset/Austausch@back-script-20240214-091014

when started in a screen session it works:

> cat 2024-02-22_09-42-09-backup.log
> Running on freebsd
> ########## Backup of pools on NAS-YVP ##########
> Started Backup-job: 2024-02-22_09-42-09
> 
> +--------------+--------+------------+--------+
> |Dataset       |Size    |Snapcount   |SnapSize |
> +--------------+--------+------------+--------+
> | Dataset | 3.17T | none | 0B |
> +--------------+--------+------------+--------+
> | Dataset/Austausch | 328G | none | 2.61M |
> +--------------+--------+------------+--------+
> | Dataset/Org | 496G | none | 30.1M |
> +--------------+--------+------------+--------+
> | Dataset/Projekte | 2.33T | none | 1.08G |
> +--------------+--------+------------+--------+
> | Dataset/ProjekteIntern | 32.2G | none | 37.4M |
> +--------------+--------+------------+--------+
> | Dataset/ScanOrdner | 773M | none | 1.17M |
> +--------------+--------+------------+--------+
>   pool: pool-backup2
>  state: ONLINE
>   scan: scrub repaired 0B in 1 days 00:06:26 with 0 errors on Thu Jan 25 10:16:29 2024
> config:
> 
> 	NAME                                          STATE     READ WRITE CKSUM
> 	pool-backup2                                  ONLINE       0     0     0
> 	  gptid/bd972045-b0af-11ee-810a-ece7a7077b48  ONLINE       0     0     0
> 
> errors: No known data errors
> 
> ****************** data / Dataset ******************
> most current snapshot in Backup: pool-backup2/Dataset@back-script-20240222-075532
> new snapshot created: data/Dataset@back-script-20240222-094233
> Send: data/Dataset@back-script-20240222-094233 to pool-backup2/Dataset
> Destroying Snapshots for Dataset:
> pool-backup2/Dataset@back-script-20240214-091013
> data/Dataset@back-script-20240214-091013
> 
> ****************** data / Dataset/Austausch ******************
> most current snapshot in Backup: pool-backup2/Dataset/Austausch@back-script-20240214-091014
> new snapshot created: data/Dataset/Austausch@back-script-20240222-094234
> Send: data/Dataset/Austausch@back-script-20240222-094234 to pool-backup2/Dataset/Austausch
> Destroying Snapshots for Dataset/Austausch:
> pool-backup2/Dataset/Austausch@back-script-20240207-144818
> data/Dataset/Austausch@back-script-20240222-075532
> data/Dataset/Austausch@back-script-20240214-091014
> data/Dataset/Austausch@back-script-20240214-091013
> 
> ****************** data / Dataset/Org ******************
> most current snapshot in Backup: pool-backup2/Dataset/Org@back-script-20240214-091015
> new snapshot created: data/Dataset/Org@back-script-20240222-094235
> Send: data/Dataset/Org@back-script-20240222-094235 to pool-backup2/Dataset/Org
> Destroying Snapshots for Dataset/Org:
> pool-backup2/Dataset/Org@back-script-20240207-144819
> data/Dataset/Org@back-script-20240222-075532
> data/Dataset/Org@back-script-20240214-091015
> data/Dataset/Org@back-script-20240214-091013
> 
> ****************** data / Dataset/Projekte ******************
> most current snapshot in Backup: pool-backup2/Dataset/Projekte@back-script-20240214-091018
> new snapshot created: data/Dataset/Projekte@back-script-20240222-094237
> Send: data/Dataset/Projekte@back-script-20240222-094237 to pool-backup2/Dataset/Projekte
> Destroying Snapshots for Dataset/Projekte:
> pool-backup2/Dataset/Projekte@back-script-20240207-144819
> data/Dataset/Projekte@back-script-20240222-075532
> data/Dataset/Projekte@back-script-20240214-091018
> data/Dataset/Projekte@back-script-20240214-091013
> 
> ****************** data / Dataset/ProjekteIntern ******************
> most current snapshot in Backup: pool-backup2/Dataset/ProjekteIntern@back-script-20240214-091437
> new snapshot created: data/Dataset/ProjekteIntern@back-script-20240222-094308
> Send: data/Dataset/ProjekteIntern@back-script-20240222-094308 to pool-backup2/Dataset/ProjekteIntern
> Destroying Snapshots for Dataset/ProjekteIntern:
> pool-backup2/Dataset/ProjekteIntern@back-script-20240207-144820
> data/Dataset/ProjekteIntern@back-script-20240222-075532
> data/Dataset/ProjekteIntern@back-script-20240214-091437
> data/Dataset/ProjekteIntern@back-script-20240214-091013
> 
> ****************** data / Dataset/ScanOrdner ******************
> most current snapshot in Backup: pool-backup2/Dataset/ScanOrdner@back-script-20240214-091441
> new snapshot created: data/Dataset/ScanOrdner@back-script-20240222-094315
> Send: data/Dataset/ScanOrdner@back-script-20240222-094315 to pool-backup2/Dataset/ScanOrdner
> Destroying Snapshots for Dataset/ScanOrdner:
> pool-backup2/Dataset/ScanOrdner@back-script-20240207-144821
> data/Dataset/ScanOrdner@back-script-20240222-075532
> data/Dataset/ScanOrdner@back-script-20240214-091441
> data/Dataset/ScanOrdner@back-script-20240214-091013
> 
> ****************** pool-backup2 - Cleanup ******************
> Last Scrub for pool-backup2 was on 1706137200 (28 days ago, below 30 days-limit) - NO scrub needed...
> Finished Backup-job: 2024-02-22_09-43-17

I have no idea why. How to debug?

kind regards

**Comment by storchi** [comment]
these are existing snapshots:

> root@NAS-YVP[~/zfsbackup-main]# zfs list -t snapshot  
> NAME                                                                            USED  AVAIL     REFER  MOUNTPOINT
> boot-pool/ROOT/13.0-U6@2023-11-15-20:41:08                                     3.15M      -     1.51G  -
> boot-pool/ROOT/13.0-U6@2023-11-16-04:02:06                                     3.34M      -     1.51G  -
> boot-pool/ROOT/13.0-U6@2023-11-30-13:47:30                                     1.51G      -     1.55G  -
> data@manual-2023-12-19_13-35                                                      0B      -      139K  -
> data/.system@manual-2023-12-19_13-35                                            117K      -      854M  -
> data/.system/configs-388408e95929461db941ccc50979f8fb@manual-2023-12-19_13-35   128K      -     2.89M  -
> data/.system/cores@manual-2023-12-19_13-35                                     85.2K      -      128K  -
> data/.system/rrd-388408e95929461db941ccc50979f8fb@manual-2023-12-19_13-35      18.8M      -     20.0M  -
> data/.system/samba4@update--2023-11-16-12-04--13.0-U5.1                         176K      -      405K  -
> data/.system/samba4@update--2023-11-30-12-50--13.0-U5.3                         170K      -      416K  -
> data/.system/samba4@manual-2023-12-19_13-35                                     176K      -      437K  -
> data/.system/services@manual-2023-12-19_13-35                                  10.7K      -      128K  -
> data/.system/syslog-388408e95929461db941ccc50979f8fb@manual-2023-12-19_13-35   2.42M      -     3.05M  -
> data/.system/webui@manual-2023-12-19_13-35                                        0B      -      128K  -
> data/Dataset@manual-2023-12-19_13-35                                              0B      -      149K  -
> data/Dataset@back-script-20240222-075532                                          0B      -      149K  -
> data/Dataset@back-script-20240222-094233                                          0B      -      149K  -
> data/Dataset/Austausch@manual-2023-12-19_13-35                                 2.24M      -      327G  -
> data/Dataset/Austausch@back-script-20240222-094233                                0B      -      328G  -
> data/Dataset/Austausch@back-script-20240222-094234                                0B      -      328G  -
> data/Dataset/Org@manual-2023-12-19_13-35                                       15.0M      -      496G  -
> data/Dataset/Org@back-script-20240222-094233                                      0B      -      496G  -
> data/Dataset/Org@back-script-20240222-094235                                      0B      -      496G  -
> data/Dataset/Projekte@manual-2023-12-19_13-35                                  1.05G      -     2.31T  -
> data/Dataset/Projekte@back-script-20240222-094233                                 0B      -     2.33T  -
> data/Dataset/Projekte@back-script-20240222-094237                                 0B      -     2.33T  -
> data/Dataset/ProjekteIntern@manual-2023-12-19_13-35                            22.8M      -     31.8G  -
> data/Dataset/ProjekteIntern@back-script-20240222-094233                           0B      -     32.2G  -
> data/Dataset/ProjekteIntern@back-script-20240222-094308                           0B      -     32.2G  -
> data/Dataset/ScanOrdner@manual-2023-12-19_13-35                                 591K      -      749M  -
> data/Dataset/ScanOrdner@back-script-20240222-094233                               0B      -      772M  -
> data/Dataset/ScanOrdner@back-script-20240222-094315                               0B      -      772M  -
> pool-backup2/Dataset@back-script-20240222-075532                                  0B      -      248K  -
> pool-backup2/Dataset@back-script-20240222-094233                                  0B      -      248K  -
> pool-backup2/Dataset/Austausch@back-script-20240214-091014                     1008K      -      324G  -
> pool-backup2/Dataset/Austausch@back-script-20240222-094234                        0B      -      324G  -
> pool-backup2/Dataset/Org@back-script-20240214-091015                           15.5M      -      494G  -
> pool-backup2/Dataset/Org@back-script-20240222-094235                              0B      -      494G  -
> pool-backup2/Dataset/Projekte@back-script-20240214-091018                       703M      -     2.29T  -
> pool-backup2/Dataset/Projekte@back-script-20240222-094237                         0B      -     2.29T  -
> pool-backup2/Dataset/ProjekteIntern@back-script-20240214-091437                14.6M      -     31.9G  -
> pool-backup2/Dataset/ProjekteIntern@back-script-20240222-094308                   0B      -     32.0G  -
> pool-backup2/Dataset/ScanOrdner@back-script-20240214-091441                     604K      -      770M  -
> pool-backup2/Dataset/ScanOrdner@back-script-20240222-094315                       0B      -      770M  -

**Comment by Pitastic** [comment]
Seems that something is crashing the snapshot creation. It simply comes down to this command what never finishes:


https://github.com/dapuru/zfsbackup/blob/16ba4178c026f28dbb7cef6bfc08d588e6e011f1/truenas-poolbackup.sh#L353

I have no idea why this is just the case when it runs from `devd`. Can you reproduce this behaviour every time? Is it always at the same Dataset or random?

To get more information why the line above fails you may edit the line above and add the verbosity flag:

```bash
zfs snapshot -v -r $NEWSNAP
```

**Comment by storchi** [comment]
Thanks for your post.
Yes, it is reproducable. It is always at the first child dataset.
I will add some debug logging...

with the -v option it stops on creating the first snapshot 

i added a "sleep 2" before "create snapshot" - now it works. Next backup day is next week. We will see.

I am also wondering about this:
> +--------------+--------+------------+--------+
> |Dataset |Size |Snapcount |SnapSize |
> +--------------+--------+------------+--------+
> | Dataset | 3.17T | none | 0B |
> +--------------+--------+------------+--------+
Why is snapcount always none?

kind regards

**Comment by Pitastic** [comment]
Interesting. So it is a race condition...Maybe there are heavy i/o operations pending on that dataset while you're trying to snapshot it?

Regarding your second question: I will have to check the code in the next days...

**Comment by storchi** [comment]
No, it is idle most of the time.

**Comment by storchi** [comment]
> i added a "sleep 2" before "create snapshot" - now it works. Next backup day is next week. We will see.

it did work again. 
Mention my dataset structure with one parent dataset and many child datasets.
vg

**Comment by dapuru** [comment]
closed, added sleep 2; Thanks @storchi @Pitastic
