### ISSUE TITLE
fail when triggered by devd

### ISSUE THREAD

**Issue by storchi** [dapuru/zfsbackup#2]
hi,

i get: 
"****************** data_pool / xxxx ******************
ERROR - No snapshot found..."
via mail when the script is triggered by devd.

triggered from console everything works fine.

what can i do?

kind regards

**Comment by dapuru** [comment]
This indicates for the mentioned dataset, there is no initial backup present yet. Try creating this initial backup first, by running the script in console. You should be presented with a dialog "There is no backup-snapshot in ${BACKUPPOOL}/${DATASET}. Should a new backup be created?" Answer with yes and continue. A message "Initializing Snapshot.." should appear.
Hope this helps, Daniel

**Comment by storchi** [comment]
the initial backup was made from console and is present
second start from console also works
christian

**Comment by dapuru** [comment]
Strange, what does the following command show (replace the variables accordingly)?
zfs list -rt snap -H -o name "${BACKUPPOOL}/${DATASET}" | grep "@${PREFIX}-" | tail -1 | cut -d@ -f2

**Comment by storchi** [comment]
on console it shows: 
zfs list -rt snap -H -o name "ext_usb1_pool/Verlag" | grep "@prefix" | tail -1 | cut -d@ -f2
prefix-20211222-122651
via devd it is empty

**Comment by dapuru** [comment]
Currently i don't have any ideas, i'll look into it, when i've time. What version of TrueNAS are you running? Did it work anytime earlier?

**Comment by storchi** [comment]
TrueNAS Version: TrueNAS-12.0-U7
it is the first time i am using TrueNAS and your script.
Thanx for your help

**Comment by storchi** [comment]
it is a timing issue. my workaround: sleep 10 before and after import backuppool. 
it was working from console, because pool was already imported.
greetings

**Comment by dapuru** [comment]
Thanks for getting back with the solution. Br
Edit: Feel free to add a pull request :-)
