### ISSUE TITLE
run scripts as non-root user

### ISSUE THREAD

**Issue by b4n4n377** [dapuru/zfsbackup#3]
Dear dapuru, 

i found this repo via https://esc-now.de/_/zfs-offsite-backup-auf-eine-externe-festplatte/?lang=en where you also posted something, I guess. 

Did you manage to run your backup scripts as a non-root user or does is have to run in root context ?

Bests
Banane

**Comment by dapuru** [comment]
Hi Banane,
i'm currently running the script as root.
I did not try otherwise yet.
best regards,
Daniel

**Comment by dapuru** [comment]
Closed. See also:
https://www.truenas.com/community/threads/import-export-zpool-via-bash-script-as-non-root.98254/
