### ISSUE TITLE
initial scrub logic fails

### ISSUE THREAD

**Issue by storchi** [dapuru/zfsbackup#4]
hi,
if
scrubRawDate=$(zpool status $BACKUPPOOL | grep scrub | awk '{print $15 $12 $13}')
is empty (because there was no scrubing before)
we get a confusing error message in status mails.
i am not able to correct this, sorry.
regards

**Comment by dapuru** [comment]
Could you please attach the error message? Thanks & br, Daniel

**Comment by storchi** [comment]
We get:
ERROR: Scrub raw date is formatted wrong.

**Comment by dapuru** [comment]
Please check out the latest commit. I changed the regex (failed before) and added some new command-line parameter. Also try running a manual scrub before running the script. best regards, Daniel

**Comment by dapuru** [comment]
Will check, but could be a little later..
