### ISSUE TITLE
False detection of bad pool shape

### ISSUE THREAD

**Issue by Pitastic** [dapuru/zfsbackup#5]
### Thank you and [esc-now.de](https://esc-now.de/_/zfs-offsite-backup-auf-eine-externe-festplatte/?lang=en) for this pretty script.

I am about to tweak and use it for my purposes.

I am running `TrueNAS on FreeBSD 12.2-RELEASE-p12` . One or two updates ago there was introduced a new ZFS feature upgrade which I decided not to upgrade to. Therefore there is a liitle hint in `zpool status`which looks like this (for every pool with this zfs version):

```
  pool: freenas-boot
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: scrub repaired 0B in 00:00:50 with 0 errors on Sat Apr 16 03:45:50 2022
config:

	NAME          STATE     READ WRITE CKSUM
	freenas-boot  ONLINE       0     0     0
	  ada0p2      ONLINE       0     0     0

errors: No known data errors
```

Your regex for pool health looks among other things for 'UNAVAIL' and hit the info message. Although the pool is healthy.

Maybe this is an edge case but the following line needs to be tuned a bit to be more precise:

https://github.com/dapuru/zfsbackup/blob/aa60e76ce212de8e82a1d40bc53c2a74331118f4/truenas-poolbackup.sh#L149

A quick but little nasty fix could be

```
zpool status | egrep -i '(DEGRADED|FAULTED|OFFLINE|UNAVAIL|REMOVED|FAIL|DESTROYED|corrupt|cannot|unrecover)' | grep -v "features are unavailable"
```

**Comment by dapuru** [comment]
Thanks, i could not test this in my maschine, but sounds ok. Merge will follow.

**Comment by Pitastic** [comment]
I tested it on my TrueNas yesterday. Thanks

Daniel ***@***.***> schrieb am Di., 19. Apr. 2022, 15:27:
