### ISSUE TITLE
Yes to all Option

### ISSUE THREAD

**Issue by Pitastic** [dapuru/zfsbackup#8]
I got ca. 10 datasets, most of them (especially the iocage) have subdatasets. Some of them are big, some of them are small.

On my initial backup I have to watch and reconnect to the script process for 24 hours because of the questions, if a new folder should be created on the (empty/clean) backup HDD. Because of the childdatasets there are tons of questions over the whole day.

I think the security question is not necessary at initial backups (hdd is clean) nor for childdatasets (if there were data, the parent already wiped it).

I would add an option for the command line to skip any `"No snapshot found"` question.

**Comment by dapuru** [comment]
Thanks, nice additions. Merge will follow.
